### ISSUE TITLE
Poor wording in Concepts/Contracts/Smart Contracts

### ISSUE THREAD

**Issue by akb-tokenized** [tokenized/docs#10]
The following could be worded better:

"The smart contract is responsible for monitoring the state of the contract and for controlling actions that affect the terms and state of the contract with respect to the terms and state of the contract, at the time the request action was received."

**Comment by KarlTheProgrammer** [comment]
Do you have a specific suggestion?

**Comment by akb-tokenized** [comment]
Accurate? Any better?

"The smart contract service is responsible for monitoring data that effect the state of the smart contract and for incorporating those changes into the contract."

**Comment by eamesyi** [comment]
That's an improvement.  Fixed.
