### ISSUE TITLE
Fees / Dust

### ISSUE THREAD

**Issue by akb-tokenized** [tokenized/docs#13]
As I read the docs I'd like to get a sense of the cost of using the framework - perhaps a fees section that addresses this. The mining fees, the product fees, the total level of dust required (there seems to be a lot of dust in some of the examples)

**Comment by eamesyi** [comment]
FYI the dust threshold limit value will be changed in the Bitcoin SV protocol to 1 satoshi soon.  

We will address the costs more accurately within the app and we are currently working on a more accurate fee estimation algorithm.  I'd like to avoid putting numbers in the docs that are subject to change, however, this will be an important part of the value proposition that will find its way into our home page, marketing material and FAQ, etc.
