### ISSUE TITLE
Frozen tokensvotes block corporate actions (votes)

### ISSUE THREAD

**Issue by akb-tokenized** [tokenized/docs#15]
Do I understand correctly:

Depending on the voting rules if tokens are frozen and thus they can not vote this may render all voting blocked as it may not be possible to get the required majority nor possible for an amendment to the majority rules to be processed as there is no voting?!

If this is not the case do the docs need to make this clear.

**Comment by eamesyi** [comment]
Upon reconsideration, I believe this is a fair point.  Users with frozen tokens probably should continue to have the ability to partake in corporate actions, for most use cases. However, we may want a flag to permit/prevent voting in the enforcement order for more 'severe' instances where control of the organization/corporate actions may be undesirable.  

I'll raise this as an issue on specification.

**Comment by eamesyi** [comment]
Issue raised.
