### ISSUE TITLE
Thaw if part of a block

### ISSUE THREAD

**Issue by akb-tokenized** [tokenized/docs#16]
Is is possible to thaw part of a frozen block. i.e. 100 tokens are frozen and 40 need to be thawed

From the docs it reads as though the whole block will  have to be thawed and then 60 tokens will have to be re-frozen. If this is the case then there is a risk that the 60 may be transferred in the interval before the re-freeze.

If this is not the case then perhaps worth clarifying in the docs.

**Comment by eamesyi** [comment]
If 100 tokens are frozen and 40 need to be thawed without risking a transfer in the 'interval', the process works like this:

1. issue a new freeze order for 60 tokens.
2. issue a thaw order for the freeze order that froze 100 tokens.
3. 40 tokens are now available to transfer by the owner, 60 tokens remain frozen under a different freeze order.

Thaw orders always refer to a specific freeze order.

@KarlTheProgrammer just double-checking that the logic continues to work the way I've described above ^
