### ISSUE TITLE
Tokens representing shares

### ISSUE THREAD

**Issue by akb-tokenized** [tokenized/docs#19]
• Share may settle via more than one settlement system and thus have multiple settlement codes 
	• Share may be listed on multiple exchanges and thus have multiple exchange codes
	• Share may be linked / relasted to other shares which are ADRs or listed on other exchanges. You may wish to have a linked token field to relate them to each other.

**Comment by eamesyi** [comment]
Can you please elaborate.

**Comment by akb-tokenized** [comment]
A bond may have multiple settlement methods:
HSBC Holdings plc 4% 03/22 - CUSIP 404280AN9, ISIN US404280AN99

Share listed multiple places / linked
HSBC listed in UK LSE (£), HK SE (HKD), Bermuda SE ($), Euronext Paris (EUR), NY SE (ADR, $)

So it is possible to get exposure to HSBC via multiple exchanges and in their respective currencies. 
I guess you would issue one token for each combination and populate a tag on the token that relates it back to the corporate entity to which it relates?

**Comment by eamesyi** [comment]
Yes, this can be handled with different AssetIDs and even different smart contracts where appropriate.
