### ISSUE TITLE
Specification / Resources / Currencies

### ISSUE THREAD

**Issue by akb-tokenized** [tokenized/docs#20]
The EUR entry in https://github.com/tokenized/specification/blob/master/src/resources/develop/Currencies.yaml is incorrect for some countries including Latvia. It seems to list the countries that are associated with the EU rather than the EURO

**Comment by eamesyi** [comment]
The list is correct.  Latvia is listed as using the EURO on wiki.  I removed EU because that doesn't make sense but the rest I've double checked
