### ISSUE TITLE
On-shore / off-shore currencies

### ISSUE THREAD

**Issue by akb-tokenized** [tokenized/docs#21]
For some of the currencies listed there are trading / holding restrictions which may cause there to be an on-shore and an off-shore version of the currency. This means that you need to be clear which currency a token relates to and be aware that as each eCurrency is representing 100% holding in the underlying currency it may not be possible for you to hold the on-shore currency so will not be able to offer the eCurrency.

**Comment by eamesyi** [comment]
This can be handled with different asset types and therefore different trading restrictions for each asset type, all operating from the same smart contract.  Or with different smart contracts and different asset types with different restrictions but still the same 'currency'.
