### ISSUE TITLE
Funding - accrual on tokens

### ISSUE THREAD

**Issue by akb-tokenized** [tokenized/docs#22]
Where tokens represent an asset and that assets has funding / carry costs have you considered how this will be handled? The docs are silent on this. 

Example: 
- shares receive dividends
- debt receives coupons
- currencies earn interest / or in the case of some charge interest to hold a positive balance
- physical assets such as gold have storage costs (negative income)
- physical assets such as property have management / maintenance costs

**Comment by eamesyi** [comment]
I have chosen to refrain from providing examples of use cases involving financial instruments until we've got our EMI license and have finished the app.  I have a number of reasons for this.

I do have a plan for all of those scenarios, but I don't wish to share that on here at the moment.  We can discuss offline.
