### ISSUE TITLE
DNS for contract addresses?

### ISSUE THREAD

**Issue by akb-tokenized** [tokenized/docs#23]
You mention the example where the contract address for a popular token such as eEUR is well known and thus one does not have to figure this out from the pkh. I wonder whether a service similar to DNS for reverse name lookup would be helpful with each token broadcasting its address to the top node DNS servers together with a time-to-live

**Comment by eamesyi** [comment]
Yes, I have a plan for something similar.  To be discussed offline.  In general, financial services companies (eg. wallet service providers) will act as guardians/curators for their customers and company domains will be used to confirm the association/legitimacy of contract PKHs.
