### ISSUE TITLE
Wallet vs 'Wallet+Smart Contract Service'

### ISSUE THREAD

**Issue by akb-tokenized** [tokenized/docs#24]
In the docs there is repeated mention of the fact that the smart contract logic operates within the wallet of a given token issuer. 

I would expect that most folks will have:
- a wallet that hold assets (tokens), reports on the quantity held and allows operations on those tokens - buy / sell / vote etc
- a smart contract service that executes the rules associated with a token issued by a given party. I would expect that for all but the most sophisticated folks this will be out-sourced to a trusted party that has the skill to set up the contracts and run /maintain the code. 

I find the reference to the smart contract logic running in the wallet very alien to what I think a wallet is. For me it is a dumb container that hold stuff. Not a logic engine that does all this complicated stuff. 
I think it is confusing in the docs and operationally the code base would be much simpler to maintain if the wallet functionality were just a container with reporting & basic buy / sell /vote operations.

**Comment by eamesyi** [comment]
Can you point me to where it says that?

**Comment by akb-tokenized** [comment]
So I was confused on two fronts.
A "smart contract" is in fact a smart contract service that operates a given contract that watches messages sent to a given address.
"The smart contract can only respond to instructions it receives as Tokenized transactions into its own wallet" - I guess I see a wallet as a holder of tokens but here it is also being used as a communications address.

Nomenclature so issue closed unless you wish to clarify the docs.
