### ISSUE TITLE
Docs style comments

### ISSUE THREAD

**Issue by akb-tokenized** [tokenized/docs#26]
Docs are always a nightmare as they are inevitably behind the code and have to appeal to a broad audience. 

I find the current docs somewhere between an overview and an implementation doc and wonder whether they could be split into:

- tech docs that are auto generated from the code (similar to JavaDocs) depending on the language used. This will have the benefit that the tech docs are always up to date.
- a user & high level concept doc that focuses more on the top level concept of all data is on the block chain, how data moves, security, transparency, protections, cost, speed, use cases etc

**Comment by eamesyi** [comment]
It has largely been done along those lines.  

The Concepts section is the user & high-level concept docs that are manually kept up to date.

The Specification is largely auto-generated from the code.

This is an evolving piece of work though, and specific suggestions are always welcome.

@daftspunk do you have anything to add here?
