### ISSUE TITLE
Binary usage flags

### ISSUE THREAD

**Issue by akb-tokenized** [tokenized/docs#27]
Why are the authorisation flags so complicated? Binary?!

If binary is necessary for storage reasons then this looks like an implementation detail that should be in the tech docs.

**Comment by eamesyi** [comment]
how would you do them differently?

**Comment by akb-tokenized** [comment]
Binary is fine for the protocol but following my other comment it feels like a low of detail for the average user who one wants to hook when they come to the website. Perhaps the implementation of the flag should be in a tech doc. As per our other exchange this doc is currently performing two roles and may evolve in time. 

Matter closed
