### ISSUE TITLE
Smart Contract Templates

### ISSUE THREAD

**Issue by akb-tokenized** [tokenized/docs#28]
The docs is silent on whether the user will have to do all the heavy lifting and produce templates from scratch; which would be scary for most folks. Few folks will want to code. 

I think it would be helpful to comment on how Tokenized will add value by providing a library of templates (some reg compliant) for various token types together with sample legal docs, corp governance templates and advise on how to put the whole thing together. 

If any have been produced them it would be good to publish them

**Comment by eamesyi** [comment]
This is a WIP and is part of the reason for the app.  We need to lead by showing.  Our app will provide all of the standard templates/legal docs, corp governance templates, etc.

I have refrained from giving too much specific advice at the protocol level and in the docs, but I fully intend to make this very easy as time goes on.  Can't share everything on here at the moment.
