### ISSUE TITLE
Sandbox / Play area

### ISSUE THREAD

**Issue by akb-tokenized** [tokenized/docs#29]
I know a beta app is on the horizon but in the meantime and for those folks that do not want to download something do you have a working demo that you could host in testnet and accessible via the website that allows one to generate actual messages onto the blockchain and play with the functionality. 

This would go some way to showing folks that this tech is real and works not vapour ware.

**Comment by eamesyi** [comment]
Yes, we are nearly finished exactly that.  We also host a smart contract for devs to play with.

@daftspunk can advise on ETA for the message generator features for the website.
