### ISSUE TITLE
News / Media

### ISSUE THREAD

**Issue by akb-tokenized** [tokenized/docs#32]
Need, ideally, one news item relating to Tokenized per month at least in here. I'm sure there is lots to talk about. Having no news in the News section is not good. Perhaps replace with CEO Blog - James you have lots to share with folks and could comment weekly. This would, undoubtedly, be picked up by the media and generate new, which could then go in the news section.

Add a register interest / get newsletter option with CRM tracking tools to see who is actually reading the news / is interested.

These 'active user' stats will be useful to be able to quote when we start to talk to investors and want examples of the size of our support group / engaged audience.

**Comment by eamesyi** [comment]
I'll chat offline with you on this.
