### ISSUE TITLE
Check page headers

### ISSUE THREAD

**Issue by daftspunk** [tokenized/docs#4]
All pages should include a **Primary Header**. Some are missing (see below). Check over each page to make sure it is the case. The basic structure should appear as so:

The header 1 will always be removed and should only ever appear at the top of the page as a reference.

```
# Internal Header (invisible header to match the Table of Contents)

- [Breadcrumb 1](#anchor-name)
- [Breadcrumb 2](#other-anchor)

<a name="anchor-name"></a>
## Primary Header/ First Section (this is missing from some pages)

Content

<a name="other-anchor"></a>
## Second Section

Content

### Secondary Header

Content
```

All the pages under Specification are generated from the specification repo.

### How to compile generated docs 

1. Clone https://github.com/tokenized/specification
1. Update the markdown `tpl` file
1. Run `make` to compile
1. Copy the `dist/markdown` files
1. Paste them in https://github.com/tokenized/docs
1. Commit and push

**Comment by the-beer-engineer** [comment]
all done
